### ISSUE TITLE
publicPaths not working

### ISSUE THREAD

**Issue by loren-m-crawford** [tho-asterist/serverless-whitelisting#4]
Hey! I'm having trouble getting publicPaths to work. Perhaps this is user error, but I've added the paths that I've defined under my function events in my serverless file but they still seem to be behind the netblocks. Can you clarify how to use publicPaths? 
```

**Comment by tho-asterist** [comment]
@loren-m-crawford 
Please try to update
`/v1/foo`
=>
`v1/foo`

**Comment by loren-m-crawford** [comment]
Hey @tho-asterist! We're using an HTTP request, but your changes still don't work. Do you have another suggestion?

**Comment by tho-asterist** [comment]
Please make sure to include `serverless-whitelisting` in plugins.
Below is the working setting in my project (I’m using python).

```
plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-whitelisting
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    layer: true
  serverless-whitelisting:
    stage: ${self:provider.stage}
    privateStages:
      - production
    netblocks:
      - <redacted>
    publicPaths:
      - v1/foo
```
