### ISSUE TITLE
Endpoints not being blocked

### ISSUE THREAD

**Issue by RaFaTEOLI** [tho-asterist/serverless-whitelisting#5]
This is my serverless.yml
```yaml
service: test-api

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs18.x

functions:
  health-check:
    handler: dist/main/server.handler
    events:
      - httpApi:
          path: /api/health-check
          method: get

custom:
  serverless-whitelisting:
    stage: ${self:provider.stage}
    privateStages:
      - dev
      - prod
    publicStages:
      - test
    netblocks:
      - 175.82.22.150

plugins:
  - serverless-offline
  - serverless-whitelisting
```

However, when I hit `/api/health-check` it doesn't block the request, and my IP is different from `175.82.22.150`
